### ISSUE TITLE
Bad values

### ISSUE THREAD

**Issue by ericrector** [ControlEverythingCommunity/SI7021#1]
Hi,

In the python code you call bus.read_byte()  2 times. These both return the same value. If you look to the datasheet, for the 0xf5 command you must do:

```
<Sr><SLAVE_ADDR_R><A><MSB><A><LSB><NA><P>
```

but issuing the 2 read_byte() commands give us:

```
<S><SLAVE_ADDR_R><A><MSB><A><P>
<S><SLAVE_ADDR_R><A><MSB><A><P>
```

I hooked the SDA/SCL lines to the scope to verify this.

![scope_0](https://cloud.githubusercontent.com/assets/17121871/16840450/0f4c2938-49d5-11e6-81ee-8c9fbe1bead6.png)

I have been through the python smbus documentation and can not find any read function to give what the Si7021 requires.

Any ideas?

**Comment by fabbronet** [comment]
take a look at my fork for updated python smbus commands [https://github.com/fabbronet/SI7021/tree/master/Python](https://github.com/fabbronet/SI7021/tree/master/Python)

**Comment by zaphod-42** [comment]
fixed in #2

**Comment by Bertolius** [comment]
I have tried to use the updated Python code on Raspi.  I just get I/O errors on the bus.read_i2c_block_data  from both temperature and humidity addresses.

**Comment by zaphod-42** [comment]
Is your I2C bus enabled? Those I/O errors are frequently indicative of a disabled I2C Bus.
